version: '3.8'

services:

  gateway:
    build: ./gateway
    image: gateway_image
    container_name: "gateway"
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Europe/Moscow

  server:
    restart: on-failure
    build: ./server
    image: server_image
    container_name: "server"
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Europe/Moscow

  db:
    image: postgres:14.7-alpine
    container_name: "db"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Europe/Moscow