version: '3.8'

services:

  gateway:
    build: gateway
    image: gateway_image
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SERVER_PORT=8080
      - SHAREIT_SERVER_URL=http://server:9090
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  server:
    build: server
    image: server_image
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  db:
    image: postgres:15.1-alpine
    container_name: postgres_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"